name: Continuous Integration
on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install spatialite
      run: |
        sudo apt-get update
        sudo apt-get install sqlite3 libsqlite3-mod-spatialite
        sudo dpkg -L libsqlite3-mod-spatialite
    - name: Build and Install tippecanoe
      run: |
        git clone https://github.com/mapbox/tippecanoe.git
        cd tippecanoe
        sudo make -j
        sudo make install
        cd ..
    - name: Make makerules
      run: |
        make makerules
    - name: Make Init
      run: |
        make init
    - name: Lint, Test, Coverage
      run: |
        make test
    - name: Collect
      run: |
        make collect
    - name: Build
      run: |
        make build
        make postprocess
        make generate-tiles
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Push
      run: |
        make push
